// EndPortal_Parallax.frag
// ---------------------------------------------------------------------------
// MCBE end_portal.fragment -> Sky:CotL engine port (single draw / in-fragment loop layering)
//
// Layers are generated by LAYER_COUNT loop iterations, each iteration equivalent
// to one draw in the original:
//   d = 0 .. LAYER_COUNT-1, perform one ray-plane intersection for the virtual
//   starfield plane at depth d, obtain UV for that layer, sample the starfield
//   and accumulate with attenuation (1 - d/MAX_LAYER_DEPTH).
//
// Changes versus the “one draw per layer” version:
//   - Intersection moved here from the vertex stage. The original interpolated
//     UV to the fragment was an approximation (the true intersection w.r.t.
//     screen position is a projective function, not linear); per-fragment
//     intersection eliminates this approximation.
//   - Requires u_eyePos / u_levelTime from PerFrameUniforms, so this stage
//     also binds that UBO.
//   - The sentinel layer (the original's w≈1 “clear-to-black” baseplate) is no
//     longer needed: accumulation starts from black, and fog is mixed only once
//     after the loop, removing the dependency on cross-draw additive blending pairs.
//
// Performance: ~8 sin calls per loop body (7 rand + 1 rotate2d), executed
//       LAYER_COUNT times, i.e. ~8 * LAYER_COUNT sin per fragment. glslc at
//       both -O0 and -O does not unroll this loop (OpLoopMerge preserved),
//       so code size is independent of LAYER_COUNT, but runtime cost scales
//       linearly with it. LAYER_COUNT is the primary performance knob for this
//       shader; reduce it when screen coverage is large.
// ---------------------------------------------------------------------------

#version 460

precision mediump int;
precision highp float;

#ifdef VULKAN
  #define UNIFORM(_Set, _Binding) layout (set = _Set, binding = _Binding) uniform
  #define UNIFORM_140(_Set, _Binding) layout (set = _Set, binding = _Binding, std140) uniform
#else
  #define UNIFORM(_Set, _Binding) layout (binding = _Binding) uniform
  #define UNIFORM_140(_Set, _Binding) layout (binding = _Binding, std140) uniform
#endif

// - Uniforms.

// ---------------------------------------------------------------------------
// Reserved: texture sampling interface
//
// Set to 1 to switch back to the original dual-texture scheme (TEXTURE_0 star
// map + TEXTURE_1 layer color LUT). Made a compile-time switch rather than a
// pure comment so this code actually participates in compilation checks, and
// when disabled, no unused sampler appears in the reflection table.
//
// set / binding must follow Sky's material descriptor conventions — the
// template has no samplers, and the two values below are placeholders;
// they must be verified before integration.
// Also note: u_starTex needs REPEAT addressing, and parallax UV values are unbounded.
// ---------------------------------------------------------------------------
#define USE_PORTAL_TEXTURES 0

#if USE_PORTAL_TEXTURES
UNIFORM(1, 0) sampler2D u_starTex;   // Corresponds to MCBE TEXTURE_0
UNIFORM(1, 1) sampler2D u_colorLut;  // Corresponds to MCBE TEXTURE_1
#endif

layout (location = 0) in highp vec3 v_worldPos;
layout (location = 1) flat in mediump vec3 v_planeNormal;
layout (location = 2) flat in highp vec3 v_eyePos;
layout (location = 3) flat in highp float v_levelTime;

layout (location = 0) out vec4 o_fragColor0;

#define PI 3.1415926

// ---------------------------------------------------------------------------
// Tunable constants
// ---------------------------------------------------------------------------

// Number of starfield planes rendered in a single draw. This is the primary
// performance knob for this shader. MCBE / MCJE use 15 layers.
const int LAYER_COUNT = 15;

// Normalization denominator for brightness attenuation. Kept at MCBE's 32.0
// to preserve the original look (brightness decays from 1.0 to 0.5625 at
// 15 layers), decoupled from LAYER_COUNT.
const float MAX_LAYER_DEPTH = 32.0;

// Tiling period of the star texture, in world units.
// MCBE uses 16.0 (= 16 blocks). Sky's world unit is not blocks; recalibrate
// by visual appearance.
const float STAR_TILE_SIZE = 16.0;

// Rotation step for inter-layer decorrelation. 5/7 ensures no two layers
// share the same orientation within 14 layers (the smallest positive integer
// solution to d * 5PI/7 = 2PI*k is d = 14). Do not change to tidy angles
// like PI/2.
const float LAYER_ROTOR = PI * (5.0 / 7.0);

// UV scroll speed along the v direction (unit: texture periods / second).
// MCBE uses 1/256.
const float SCROLL_SPEED = 1.0 / 256.0;

// Grazing-angle guard: t diverges as dot(viewRay, planeNormal) approaches zero.
const float MIN_COS = 1.0e-4;

// UV fold-back period. See explanation in main().
const float UV_FOLD = 64.0;

// Overall gain. The original template sums 5 layers then multiplies by 0.15;
// recalibrate when the layer count changes.
const float STAR_GAIN = 0.15;

// ---------------------------------------------------------------------------
// Original procedural starfield from the template (algorithm preserved)
// ---------------------------------------------------------------------------

float rand(vec2 pos) {
  return fract(sin(dot(pos, vec2(23.2342, 82.29561))) * 82931.1857193);
}

mat2 rotate2d(float angle) {
  return mat2(
    sin(angle), -cos(angle),
    cos(angle), sin(angle)
  );
}

// Scalar portion extracted from the template's pattern(): returns the
// star-point density at the given UV. The split separates "density" from
// "coloring" to match the original textureSample.rgb * colorSample.rgb
// structure. time is passed in from gsu.u_levelTime (the template referenced
// it directly as a varying global).
float starDensity(vec2 pos, float size, float frequency, float angle, float time) {
  pos *= rotate2d(angle);
  vec2 c = pos * size;
  float d = floor(rand(floor(c + vec2( 0.0 + time,  0.0))) + frequency)
    + 0.4 * floor(rand(floor(c + vec2(-1.0 + time,  0.0))) + frequency)
    + 0.2 * floor(rand(floor(c + vec2(-2.0 + time,  0.0))) + frequency)
    + 0.1 * floor(rand(floor(c + vec2( 0.0 + time, -1.0))) + frequency)
    + 0.1 * floor(rand(floor(c + vec2( 0.0 + time,  1.0))) + frequency)
    + 0.1 * floor(rand(floor(c + vec2( 1.0 + time,  0.0))) + frequency);
  return d * (1.0 - 0.5 * rand(floor(c + vec2(-1.0 + time, 0.0))));
}

// ---------------------------------------------------------------------------
// Layer parameter table — replaces TEXTURE_0 / TEXTURE_1
//
// The template originally superposed 5 sets of (size, frequency, angle) in a
// single fragment. After porting, it became "one set per layer": the layer
// index determines star density, scale, and coloring — deeper layers use
// smaller, denser stars; shallower layers use larger, sparser stars.
// The palette is taken from the 5 color sets given in the template's comments.
// ---------------------------------------------------------------------------

const int STAR_VARIANTS = 5;

// xyz = (size, frequency, angle)
const vec3 STAR_PARAMS[STAR_VARIANTS] = vec3[](
  vec3(1.0, 0.008, PI / 7.0),
  vec3(0.5, 0.008, PI / 3.0),
  vec3(0.25, 0.008, 3.0 * PI / 4.0),
  vec3(0.125, 0.008, 5.0 * PI / 4.0),
  vec3(0.0625, 0.008, PI)
);

const vec3 STAR_PALETTE[STAR_VARIANTS] = vec3[](
  vec3( 76.0, 149.0, 156.0) / 255.0,
  vec3( 33.0,  96.0, 198.0) / 255.0,
  vec3( 85.0, 184.0, 130.0) / 255.0,
  vec3( 74.0, 160.0, 115.0) / 255.0,
  vec3( 47.0, 112.0, 168.0) / 255.0
);

void main() {
  vec3 n = normalize(v_planeNormal);

  // View ray. a_position is in absolute world coordinates, so we must
  // subtract the eye position (in MCBE, worldPos is already camera-relative
  // and usable directly).
  vec3 viewRay = v_worldPos - v_eyePos;

  // s = dot(viewRay, n) is also the signed distance from the camera to the
  // plane containing this face — constant across the entire face, shared by
  // all layers.
  float s = dot(viewRay, n);
  // The original lacks this guard; s crossing zero would propagate inf/NaN
  // into the UV.
  s = (s < 0.0 ? -1.0 : 1.0) * max(abs(s), MIN_COS);

  // floor(|n| + 0.5) yields a one-hot axis selector while also absorbing
  // quantization error from the vertex color.
  vec3 normalMask = floor(abs(n) + vec3(0.5));

  float time = v_levelTime;
  float scroll = time * SCROLL_SPEED;

  vec3 acc = vec3(0.0);

  // ---- Per-layer accumulation ----
  // Each iteration is equivalent to one draw in the original. Additive
  // accumulation is order-independent.
  for (int i = 0; i < LAYER_COUNT; ++i) {
    float d = float(i);

    // Ray-plane intersection. The original writes:
    //   dot(viewRay - d*n, n) / dot(viewRay, n)
    // Since |n| = 1, the numerator simplifies to s - d, so t = 1 - d/s.
    // Geometric meaning: the layer's plane is the surface plane pushed d
    // units along -n. d = 0 gives t = 1, i.e. the intersection is the
    // surface itself.
    float t = 1.0 - d / s;

    // Add back the eye position to recover absolute world coordinates —
    // this anchors the starfield in world space so it does not drift under
    // camera translation; parallax comes purely from t varying with view
    // direction.
    vec3 hit = viewRay * t + v_eyePos;

    // Axis-aligned projection: drop the axis corresponding to the normal.
    vec2 raycastUV = (hit.yz * normalMask.x
      + hit.xz * normalMask.y
      + hit.xy * normalMask.z) / STAR_TILE_SIZE;

    // Inter-layer decorrelation: rotation + Archimedean spiral translation.
    float ang  = d * LAYER_ROTOR;
    float rotS = sin(ang);
    float rotC = cos(ang);

    // GLSL mat2 is column-major; this is equivalent to a CCW rotation by ang.
    vec2 uv = mat2(vec2(rotC, rotS), vec2(-rotS, rotC)) * raycastUV;
    // Radius grows linearly with layer index, angle steps uniformly — ensures
    // each layer samples a different region.
    uv += vec2(rotC, rotS) * d;
    // Uniform v-direction scroll. Since each layer's UV has already been
    // rotated by ang, this single translation lands in a different direction
    // in each layer's local frame, giving inter-layer differential flow for free.
    uv.y += scroll;

    // UV fold-back. uv has three sources of unbounded growth: absolute world
    // coordinates, t diverging at grazing angles, and accumulated scroll over
    // time. starDensity internally applies floor + high-frequency sin hashing
    // on UV, which is more susceptible to precision breakdown than texture
    // sampling (large values cause neighboring pixels to hash to the same cell).
    // MCBE original has equivalent code (User story 103038) but commented out —
    // placing it in the vertex shader was wrong: interpolation across the fold
    // boundary would tear the entire quad; it is safe in the fragment stage.
    //uv = mod(uv, UV_FOLD);

    uv *= 64.0;

    int variant = i % STAR_VARIANTS;

#if USE_PORTAL_TEXTURES
    float density = texture(u_starTex, uv).r;
    // LUT now indexed by layer index rather than vertex UV — layers are
    // generated by the loop, so per-vertex layer information no longer exists.
    vec3 layerColor = texture(u_colorLut, vec2((d + 0.5) / float(LAYER_COUNT), 0.5)).rgb;
#else
    vec3  p = STAR_PARAMS[variant];
    float density = starDensity(uv, p.x, p.y, p.z, time);
    vec3  layerColor = STAR_PALETTE[variant];
#endif

    // Deeper layers are dimmer, simulating more distant, fainter stars.
    float brightness = 1.0 - d / MAX_LAYER_DEPTH;

    acc += density * layerColor * brightness;
  }

  vec3 result = acc * STAR_GAIN;

#ifdef FOG
  // TODO: The exact semantics of u_cheapFog / u_cheapFog2 have not yet been
  //       confirmed on the engine side. Implemented here under the most common
  //       convention: u_cheapFog.rgb = fog color, u_cheapFog.a = intensity,
  //       u_cheapFog2.xy = (fog start distance, fog full distance). Correct
  //       according to the actual definitions after integration.
  // After a single draw, standard fog blending can be applied directly — the
  // original cross-draw pairing of "starfield layer × (1-a) + sentinel layer
  // adds fogColor×a" is no longer needed.
  float dist  = length(viewRay);
  float range = max(gsu.u_cheapFog2.y - gsu.u_cheapFog2.x, 1.0e-4);
  float fogA  = clamp((dist - gsu.u_cheapFog2.x) / range, 0.0, 1.0) * gsu.u_cheapFog.a;
  result = mix(result, gsu.u_cheapFog.rgb, fogA);
#endif

  o_fragColor0 = vec4(result, 1.0);
}
