#ifndef __SKY_SKYGFX_HPP__
#define __SKY_SKYGFX_HPP__

#include <Utils/Types.h>

enum GfxType: u08 {
  kGfxType_UNKNOWN = 0,
  kGfxType_FLOAT,
  kGfxType_FLOAT2,
  kGfxType_FLOAT3,
  kGfxType_FLOAT4,
  kGfxType_INT,
  kGfxType_INT2,
  kGfxType_INT3,
  kGfxType_INT4,
  kGfxType_UINT,
  kGfxType_UINT2,
  kGfxType_UINT3,
  kGfxType_UINT4,
  kGfxType_HALF,
  kGfxType_HALF2,
  kGfxType_HALF3,
  kGfxType_HALF4,
  kGfxType_SHORT,
  kGfxType_SHORT2,
  kGfxType_SHORT3,
  kGfxType_SHORT4,
  kGfxType_BYTE,
  kGfxType_BYTE2,
  kGfxType_BYTE3,
  kGfxType_BYTE4,
  kGfxType_UBYTE,
  kGfxType_UBYTE2,
  kGfxType_UBYTE3,
  kGfxType_UBYTE4,
  kGfxType_USHORT,
  kGfxType_USHORT2,
  kGfxType_USHORT3,
  kGfxType_USHORT4,
  kGfxType_FLOAT3x3,
  kGfxType_FLOAT4x3,
  kGfxType_FLOAT4x4,
  kGfxType_HALF3x3,
  kGfxType_HALF4x3,
  kGfxType_HALF4x4,
};

enum GfxAttr: u08 {
  kGfxAttr_Undefined = 0,
  kGfxAttr_Position,
  kGfxAttr_Color,
  kGfxAttr_Normal,
  kGfxAttr_Tangent,
  kGfxAttr_TexCoord0,
  kGfxAttr_TexCoord1,
  kGfxAttr_TexCoord2,
  kGfxAttr_TexCoord3,
  kGfxAttr_TexCoord4,
  kGfxAttr_TexCoord5,
  kGfxAttr_TexCoord6,
  kGfxAttr_TexCoord7,
  kGfxAttr_Light0,
  kGfxAttr_Light1,
  kGfxAttr_Light2,
  kGfxAttr_Light3,
  kGfxAttr_Noise0,
  kGfxAttr_PointSize,
  kGfxAttr_Center,
  kGfxAttr_RotX,
  kGfxAttr_RotY,
  kGfxAttr_RotZ,
  kGfxAttr_Scale,
  kGfxAttr_UserData0,
  kGfxAttr_UserData1,
  kGfxAttr_UserData2,
  kGfxAttr_UserData3,
  kGfxAttr_RailInfo,
  kGfxAttr_RailBindEnd,
  kGfxAttr_RailBindUp,
  kGfxAttr_NormDepth,
  kGfxAttr_Material0,
  kGfxAttr_Material1,
};

#endif
